version: '3'

services:
  oracle:
    image: gvenzl/oracle-xe
    container_name: oracle
    ports:
      - "1521:1521"
      - "5500:5500"
    environment:
      - ORACLE_SID=XE
      - ORACLE_PDB=XEPDB1
      - ORACLE_PASSWORD=password
    volumes:
      - oracle-data:/opt/oracle/oradata

volumes:
  oracle-data: